# Generated by Django 3.2.9 on 2021-11-18 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecaller', '0002_enquiries_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiries',
            old_name='followpdate',
            new_name='followupdate',
        ),
    ]
